const data = {
  "queryCost": 1,
  "latitude": 43.7441,
  "longitude": -72.2297,
  "resolvedAddress": "33 Carriage Ln, Hanover, NH 03755, United States",
  "address": "33 carriage lane, Hanover, NH",
  "timezone": "America/New_York",
  "tzoffset": -4,
  "description": "Similar temperatures continuing with no rain expected.",
  "days": [
    {
      "datetime": "2024-05-03",
      "datetimeEpoch": 1714708800,
      "tempmax": 62,
      "tempmin": 47.4,
      "temp": 55.2,
      "feelslikemax": 62,
      "feelslikemin": 47.4,
      "feelslike": 55.2,
      "dew": 44.2,
      "humidity": 67.5,
      "precip": 0,
      "precipprob": 2,
      "precipcover": 0,
      "preciptype": null,
      "snow": 0,
      "snowdepth": 0,
      "windgust": 17.2,
      "windspeed": 6.9,
      "winddir": 140.4,
      "pressure": 1021.7,
      "cloudcover": 74.2,
      "visibility": 10,
      "solarradiation": 143.9,
      "solarenergy": 12.5,
      "uvindex": 5,
      "severerisk": 10,
      "sunrise": "05:37:36",
      "sunriseEpoch": 1714729056,
      "sunset": "19:54:43",
      "sunsetEpoch": 1714780483,
      "moonphase": 0.84,
      "conditions": "Partially cloudy",
      "description": "Partly cloudy throughout the day.",
      "icon": "partly-cloudy-day",
      "stations": [
        "F0472",
        "K1P1",
        "KLEB",
        "KVSF"
      ],
      "source": "comb",
      "hours": [
        {
          "datetime": "00:00:00",
          "datetimeEpoch": 1714708800,
          "temp": 53.6,
          "feelslike": 53.6,
          "humidity": 79.92,
          "dew": 47.5,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 2.2,
          "windspeed": 0,
          "winddir": 0,
          "pressure": 1018.4,
          "visibility": 9.9,
          "cloudcover": 100,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Overcast",
          "icon": "cloudy",
          "stations": [
            "F0472",
            "K1P1",
            "KLEB",
            "KVSF"
          ],
          "source": "obs"
        },
        {
          "datetime": "01:00:00",
          "datetimeEpoch": 1714712400,
          "temp": 53.5,
          "feelslike": 53.5,
          "humidity": 78.22,
          "dew": 46.9,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 2.2,
          "windspeed": 3.1,
          "winddir": 30,
          "pressure": 1018.8,
          "visibility": 9.9,
          "cloudcover": 100,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Overcast",
          "icon": "cloudy",
          "stations": [
            "F0472",
            "K1P1",
            "KLEB",
            "KVSF"
          ],
          "source": "obs"
        },
        {
          "datetime": "02:00:00",
          "datetimeEpoch": 1714716000,
          "temp": 52.8,
          "feelslike": 52.8,
          "humidity": 77.81,
          "dew": 46.1,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 8.1,
          "windspeed": 0,
          "winddir": 0,
          "pressure": 1019.1,
          "visibility": 9.9,
          "cloudcover": 100,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Overcast",
          "icon": "cloudy",
          "stations": [
            "F0472",
            "K1P1",
            "KLEB",
            "KVSF"
          ],
          "source": "obs"
        },
        {
          "datetime": "03:00:00",
          "datetimeEpoch": 1714719600,
          "temp": 51.6,
          "feelslike": 51.6,
          "humidity": 80.94,
          "dew": 45.9,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 6.9,
          "windspeed": 3.9,
          "winddir": 50,
          "pressure": 1019.5,
          "visibility": 9.9,
          "cloudcover": 98.7,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Overcast",
          "icon": "cloudy",
          "stations": [
            "F0472",
            "K1P1",
            "KLEB",
            "KVSF"
          ],
          "source": "obs"
        },
        {
          "datetime": "04:00:00",
          "datetimeEpoch": 1714723200,
          "temp": 51.3,
          "feelslike": 51.3,
          "humidity": 76.34,
          "dew": 44.1,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 6.9,
          "windspeed": 0.4,
          "winddir": 4,
          "pressure": 1019.8,
          "visibility": 9.9,
          "cloudcover": 94.7,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Overcast",
          "icon": "cloudy",
          "stations": [
            "F0472",
            "K1P1",
            "KLEB",
            "KVSF"
          ],
          "source": "obs"
        },
        {
          "datetime": "05:00:00",
          "datetimeEpoch": 1714726800,
          "temp": 49.4,
          "feelslike": 49.4,
          "humidity": 79.15,
          "dew": 43.2,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 6.9,
          "windspeed": 0,
          "winddir": 0,
          "pressure": 1020.4,
          "visibility": 9.9,
          "cloudcover": 34.6,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-night",
          "stations": [
            "F0472",
            "K1P1",
            "KLEB",
            "KVSF"
          ],
          "source": "obs"
        },
        {
          "datetime": "06:00:00",
          "datetimeEpoch": 1714730400,
          "temp": 47.4,
          "feelslike": 47.4,
          "humidity": 89.89,
          "dew": 44.6,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 6.9,
          "windspeed": 0,
          "winddir": 0,
          "pressure": 1021.5,
          "visibility": 8.9,
          "cloudcover": 97.9,
          "solarradiation": 10,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Overcast",
          "icon": "cloudy",
          "stations": [
            "F0472",
            "K1P1",
            "KLEB",
            "KVSF"
          ],
          "source": "obs"
        },
        {
          "datetime": "07:00:00",
          "datetimeEpoch": 1714734000,
          "temp": 50.4,
          "feelslike": 50.4,
          "humidity": 79.11,
          "dew": 44.1,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 6.9,
          "windspeed": 0,
          "winddir": 0,
          "pressure": 1022.1,
          "visibility": 9.9,
          "cloudcover": 89.3,
          "solarradiation": 28,
          "solarenergy": 0.1,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "F0472",
            "K1P1",
            "KLEB",
            "KVSF"
          ],
          "source": "obs"
        },
        {
          "datetime": "08:00:00",
          "datetimeEpoch": 1714737600,
          "temp": 51.1,
          "feelslike": 51.1,
          "humidity": 74.2,
          "dew": 43.2,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 6.9,
          "windspeed": 6.7,
          "winddir": 177,
          "pressure": 1022.5,
          "visibility": 9.9,
          "cloudcover": 89.3,
          "solarradiation": 76,
          "solarenergy": 0.3,
          "uvindex": 1,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "F0472",
            "K1P1",
            "KLEB",
            "KVSF"
          ],
          "source": "obs"
        },
        {
          "datetime": "09:00:00",
          "datetimeEpoch": 1714741200,
          "temp": 53.3,
          "feelslike": 53.3,
          "humidity": 68.4,
          "dew": 43.2,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 6.9,
          "windspeed": 3.9,
          "winddir": 165,
          "pressure": 1022.9,
          "visibility": 9.9,
          "cloudcover": 79.4,
          "solarradiation": 100,
          "solarenergy": 0.4,
          "uvindex": 1,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "F0472",
            "K1P1",
            "KLEB",
            "KVSF"
          ],
          "source": "obs"
        },
        {
          "datetime": "10:00:00",
          "datetimeEpoch": 1714744800,
          "temp": 56.7,
          "feelslike": 56.7,
          "humidity": 60.11,
          "dew": 43,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 9.2,
          "windspeed": 5.2,
          "winddir": 329,
          "pressure": 1022.6,
          "visibility": 9.9,
          "cloudcover": 84.7,
          "solarradiation": 142,
          "solarenergy": 0.5,
          "uvindex": 1,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "F0472",
            "K1P1",
            "KLEB",
            "KVSF"
          ],
          "source": "obs"
        },
        {
          "datetime": "11:00:00",
          "datetimeEpoch": 1714748400,
          "temp": 58.8,
          "feelslike": 58.8,
          "humidity": 55.97,
          "dew": 43.1,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 11.4,
          "windspeed": 3.4,
          "winddir": 283,
          "pressure": 1023,
          "visibility": 9.9,
          "cloudcover": 89.3,
          "solarradiation": 314,
          "solarenergy": 1.1,
          "uvindex": 3,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": [
            "F0472",
            "K1P1",
            "KLEB",
            "KVSF"
          ],
          "source": "obs"
        },
        {
          "datetime": "12:00:00",
          "datetimeEpoch": 1714752000,
          "temp": 61.9,
          "feelslike": 61.9,
          "humidity": 51.76,
          "dew": 43.9,
          "precip": 0,
          "precipprob": 0,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 17.2,
          "windspeed": 5.1,
          "winddir": 124,
          "pressure": 1022.2,
          "visibility": 9.9,
          "cloudcover": 93.9,
          "solarradiation": 429,
          "solarenergy": 1.5,
          "uvindex": 4,
          "severerisk": 10,
          "conditions": "Overcast",
          "icon": "cloudy",
          "stations": [
            "F0472",
            "K1P1",
            "KLEB",
            "KVSF"
          ],
          "source": "obs"
        },
        {
          "datetime": "13:00:00",
          "datetimeEpoch": 1714755600,
          "temp": 58,
          "feelslike": 58,
          "humidity": 57.46,
          "dew": 43.1,
          "precip": 0,
          "precipprob": 2,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 11.4,
          "windspeed": 6.9,
          "winddir": 130,
          "pressure": 1022,
          "visibility": 10.1,
          "cloudcover": 68,
          "solarradiation": 516,
          "solarenergy": 1.9,
          "uvindex": 5,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": null,
          "source": "fcst"
        },
        {
          "datetime": "14:00:00",
          "datetimeEpoch": 1714759200,
          "temp": 58.9,
          "feelslike": 58.9,
          "humidity": 55.64,
          "dew": 43.1,
          "precip": 0,
          "precipprob": 1,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 12.8,
          "windspeed": 6.9,
          "winddir": 140,
          "pressure": 1022,
          "visibility": 10.1,
          "cloudcover": 68,
          "solarradiation": 497,
          "solarenergy": 1.8,
          "uvindex": 5,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": null,
          "source": "fcst"
        },
        {
          "datetime": "15:00:00",
          "datetimeEpoch": 1714762800,
          "temp": 61.1,
          "feelslike": 61.1,
          "humidity": 51.52,
          "dew": 43.1,
          "precip": 0,
          "precipprob": 1,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 11.4,
          "windspeed": 6.9,
          "winddir": 140,
          "pressure": 1022,
          "visibility": 10.1,
          "cloudcover": 64,
          "solarradiation": 407,
          "solarenergy": 1.5,
          "uvindex": 4,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": null,
          "source": "fcst"
        },
        {
          "datetime": "16:00:00",
          "datetimeEpoch": 1714766400,
          "temp": 61.1,
          "feelslike": 61.1,
          "humidity": 51.52,
          "dew": 43.1,
          "precip": 0,
          "precipprob": 1,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 11.4,
          "windspeed": 6.9,
          "winddir": 150,
          "pressure": 1022,
          "visibility": 10.1,
          "cloudcover": 61,
          "solarradiation": 323,
          "solarenergy": 1.2,
          "uvindex": 3,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": null,
          "source": "fcst"
        },
        {
          "datetime": "17:00:00",
          "datetimeEpoch": 1714770000,
          "temp": 62,
          "feelslike": 62,
          "humidity": 51.65,
          "dew": 44,
          "precip": 0,
          "precipprob": 1,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 10.3,
          "windspeed": 5.8,
          "winddir": 150,
          "pressure": 1023,
          "visibility": 10.1,
          "cloudcover": 57,
          "solarradiation": 267,
          "solarenergy": 1,
          "uvindex": 3,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": null,
          "source": "fcst"
        },
        {
          "datetime": "18:00:00",
          "datetimeEpoch": 1714773600,
          "temp": 60,
          "feelslike": 60,
          "humidity": 55.41,
          "dew": 44,
          "precip": 0,
          "precipprob": 1,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 10.3,
          "windspeed": 5.8,
          "winddir": 150,
          "pressure": 1022,
          "visibility": 10.1,
          "cloudcover": 54,
          "solarradiation": 194,
          "solarenergy": 0.7,
          "uvindex": 2,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": null,
          "source": "fcst"
        },
        {
          "datetime": "19:00:00",
          "datetimeEpoch": 1714777200,
          "temp": 58,
          "feelslike": 58,
          "humidity": 59.47,
          "dew": 44,
          "precip": 0,
          "precipprob": 1,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 10.3,
          "windspeed": 5.8,
          "winddir": 140,
          "pressure": 1023,
          "visibility": 10.1,
          "cloudcover": 51,
          "solarradiation": 115,
          "solarenergy": 0.4,
          "uvindex": 1,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-day",
          "stations": null,
          "source": "fcst"
        },
        {
          "datetime": "20:00:00",
          "datetimeEpoch": 1714780800,
          "temp": 56,
          "feelslike": 56,
          "humidity": 66.55,
          "dew": 45,
          "precip": 0,
          "precipprob": 1,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 9.2,
          "windspeed": 4.7,
          "winddir": 140,
          "pressure": 1022,
          "visibility": 10.1,
          "cloudcover": 49,
          "solarradiation": 36,
          "solarenergy": 0.1,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-night",
          "stations": null,
          "source": "fcst"
        },
        {
          "datetime": "21:00:00",
          "datetimeEpoch": 1714784400,
          "temp": 54.1,
          "feelslike": 54.1,
          "humidity": 68.64,
          "dew": 44,
          "precip": 0,
          "precipprob": 1,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 8.1,
          "windspeed": 4.7,
          "winddir": 140,
          "pressure": 1023,
          "visibility": 10.1,
          "cloudcover": 50,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-night",
          "stations": null,
          "source": "fcst"
        },
        {
          "datetime": "22:00:00",
          "datetimeEpoch": 1714788000,
          "temp": 52.1,
          "feelslike": 52.1,
          "humidity": 73.81,
          "dew": 44,
          "precip": 0,
          "precipprob": 1,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 8.1,
          "windspeed": 4.7,
          "winddir": 140,
          "pressure": 1023,
          "visibility": 10.1,
          "cloudcover": 52,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-night",
          "stations": null,
          "source": "fcst"
        },
        {
          "datetime": "23:00:00",
          "datetimeEpoch": 1714791600,
          "temp": 51,
          "feelslike": 51,
          "humidity": 76.81,
          "dew": 44,
          "precip": 0,
          "precipprob": 1,
          "snow": 0,
          "snowdepth": 0,
          "preciptype": null,
          "windgust": 8.1,
          "windspeed": 4.7,
          "winddir": 140,
          "pressure": 1023,
          "visibility": 10.1,
          "cloudcover": 54,
          "solarradiation": 0,
          "solarenergy": 0,
          "uvindex": 0,
          "severerisk": 10,
          "conditions": "Partially cloudy",
          "icon": "partly-cloudy-night",
          "stations": null,
          "source": "fcst"
        }
      ]
    }
  ],
  "alerts": [],
  "stations": {
    "VTTHT": {
      "distance": 7765,
      "latitude": 43.813,
      "longitude": -72.215,
      "useCount": 0,
      "id": "VTTHT",
      "name": "I-91 - Thetford VT US VTRANS",
      "quality": 0,
      "contribution": 0
    },
    "VTWLD": {
      "distance": 9696,
      "latitude": 43.683,
      "longitude": -72.315,
      "useCount": 0,
      "id": "VTWLD",
      "name": "I-91 Wilder VT US VTRANS",
      "quality": 0,
      "contribution": 0
    },
    "F0472": {
      "distance": 9268,
      "latitude": 43.662,
      "longitude": -72.249,
      "useCount": 0,
      "id": "F0472",
      "name": "FW0472 Lebanon NH US",
      "quality": 0,
      "contribution": 0
    },
    "K1P1": {
      "distance": 38773,
      "latitude": 43.78,
      "longitude": -71.75,
      "useCount": 0,
      "id": "K1P1",
      "name": "K1P1",
      "quality": 100,
      "contribution": 0
    },
    "KLEB": {
      "distance": 13905,
      "latitude": 43.63,
      "longitude": -72.3,
      "useCount": 0,
      "id": "KLEB",
      "name": "KLEB",
      "quality": 100,
      "contribution": 0
    },
    "KVSF": {
      "distance": 49732,
      "latitude": 43.35,
      "longitude": -72.52,
      "useCount": 0,
      "id": "KVSF",
      "name": "KVSF",
      "quality": 100,
      "contribution": 0
    }
  },
  "currentConditions": {
    "datetime": "12:15:00",
    "datetimeEpoch": 1714752900,
    "temp": 63.1,
    "feelslike": 63.1,
    "humidity": 49.3,
    "dew": 43.8,
    "precip": 0,
    "precipprob": 0,
    "snow": 0,
    "snowdepth": 0,
    "preciptype": null,
    "windgust": 7.6,
    "windspeed": 4.3,
    "winddir": 155,
    "pressure": 1022,
    "visibility": 11.8,
    "cloudcover": 100,
    "solarradiation": 429,
    "solarenergy": 1.5,
    "uvindex": 4,
    "conditions": "Overcast",
    "icon": "cloudy",
    "stations": [
      "VTTHT",
      "VTWLD",
      "F0472",
      "KLEB"
    ],
    "source": "obs",
    "sunrise": "05:37:36",
    "sunriseEpoch": 1714729056,
    "sunset": "19:54:43",
    "sunsetEpoch": 1714780483,
    "moonphase": 0.84
  }
}

export default function handler(res, req) {
  console.log('heuyyyyy');
  res.status(200).json({ 'message': 'uhhh' });
}